# Site settings
title: 52dreams # 你的博客名字，可以定义修订
header-img: "img/bg-post.jpg"
tagline: "cn"  
description: "Dream,my life yearning."  # 一句话描述你的博客
baseurl: "/blog.github.io"
url: "https://spiritgs.github.io/blog.github.io"  # 此处填写你的博客地址 

# About/contact
owner: 
  name: "Andy Hunter" # 填写作者信息：名字
  email: spirit.nj@gmail.com # 填写作者信息：邮箱
  bio: "This is what about dream." # 填写作者信息：博客描述

# Data
gavatar: img/favicon.png # 浏览器地址栏小图标，可自定义更改
favicon: img/favicon.png # 浏览器地址栏小图标，可自定义更改

douban_username:  # 你的豆瓣id
twitter_username: 52dreams_
github_username: spiritgs
facebook_username: 
weibo_username: 52dreams
zhihu_username: 52dreams_

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Andy Hunter" # 你的名字
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus # 使用 disqus 评论模块，读者翻墙才能看见
  duoshuo :
    short_name :  # 填写你的 disqus id
  disqus :
      short_name :  # 填写你的 disqus id

# Analytics and webmaster tools stuff goes here
google_analytics: G-KE374S146 # 填写你  google_analytics id
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
